language: c

compiler:
    - clang
sudo: required

before_install: sudo apt-get install -y cmake libssl-dev libglib2.0-0 libgstreamer0.10-0 libgstreamer0.10-dev

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "GxBj/ymnQBqvgyNUoi8UbTWEfL7HmwVNK1AdWqBWqpXH7zhVZWiJVww6TzKTdOrS+JwS2WRITvTehvLgxaqjltnV+5FTriSQqdx6e1CuTQzNQ8us7R6Uz0LA8P05BAexzgznafKoQyXx86+KZ4ba41cQ1YJaYzb5rNDtkNtHfTU="

script: cmake . && make

addons:
  coverity_scan:
    project:
      name: "pexip/pexrtmpserver"
      description: "Build submitted via Travis CI"
    notification_email: david@pexip.com
    build_command_prepend: "cmake .; make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
