language: c

compiler:
    - gcc

sudo: true

before_install:
    - sudo add-apt-repository -y ppa:gstreamer-developers/ppa
    - sudo apt-get update
    - sudo apt-get install -y
        gir1.2-gstreamer-1.0
        git
        make
        gstreamer1.0-plugins-bad
        gstreamer1.0-plugins-base
        libgstreamer1.0-dev
        libgstreamer-plugins-base1.0-dev
        valac

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "GxBj/ymnQBqvgyNUoi8UbTWEfL7HmwVNK1AdWqBWqpXH7zhVZWiJVww6TzKTdOrS+JwS2WRITvTehvLgxaqjltnV+5FTriSQqdx6e1CuTQzNQ8us7R6Uz0LA8P05BAexzgznafKoQyXx86+KZ4ba41cQ1YJaYzb5rNDtkNtHfTU="

script: ./autogen.sh; ./configure && make

addons:
  coverity_scan:
    project:
      name: "pexip/pexrtmpserver"
      description: "Build submitted via Travis CI"
    notification_email: david@pexip.com
    build_command_prepend: "./autogen.sh; ./configure"
    build_command:   "make"
    branch_pattern: master